name: Deploy app
on:
  workflow_run:
    workflows: [React-Artifact-output-cache]
    types: [completed]

# permissions:
#    id-token: write
#    contents: read

jobs:
    on-success:
        runs-on: [self-hosted, linux, x64]
#        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
         id-token: write
         actions: read
         contents: read

        steps:
            - run: |
                echo "Run ID: ${{ github.event.workflow_run.id }}"
                echo "Workflow: ${{ github.event.workflow_run.name }}"

            - name: download artifact
              uses: actions/download-artifact@v5
              with:
                name: build-artifacts
                github-token: ${{ secrets.GHACTIONS_PAT }}
                run-id: ${{ github.event.workflow_run.id }}

            - name: Azure login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                
            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
               app-name: 'reactnative'
               package: .

              