name: Output Issues event details

on:
    issues

jobs:
    output:
        runs-on: ubuntu-latest
        steps:
         - name: output issue event context details
           run: echo "context details are ${{ toJSON(github.event) }}"