name: React JS Build

on: 
  push:
    branches: [main]
    paths:
        ["react2/**"]
  workflow_dispatch:

env:
    working-dir: "./react2"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: git checkout
              uses: actions/checkout@v6
            
            - name: install dependencies
              run: npm ci
              working-directory: ${{ env.working-dir }}

            - name: build
              run: npm run build
              working-directory: ${{ env.working-dir }}

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: linting
              run: npm i -g lint
              working-directory: ${{ env.working-dir }}

            - name: testing
              run: npm test
              working-directory: ${{ env.working-dir }}

    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: deploying the application
              run: echo "deploying app"

        

        