name: React JS Build

on: 
  push:
    branches: [main]
    paths:
        ["react-proj2/**"]
  workflow_dispatch:

env:
    working-dir: "./react-proj2"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: git checkout
              uses: actions/checkout@v6
            
            - name: install dependencies
              run: npm ci
              working-directory: ${{ env.working-dir }}

            - name: build
              run: npm run build
              working-directory: ${{ env.working-dir }}
            
            - name: listing build directory
              shell: bash
              run: |
                ls -la .
                ls -la react-proj2
                ls -la react-proj2/dist
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: react-app-build
                path: ${{ env.working-dir }}/dist
            

    deploy:
      name: Deploy to Azure Static Web Apps
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download build artifact
          uses: actions/download-artifact@v4
          with:
            name: react-app-build
            path: ${{ github.workspace }}

        - name: listing downloaded artifact
          shell: bash
          run: |
            ls -la .
            ls -la ${{ github.workspace }}
            ls -la ${{ env.working-dir }}
            ls -la react-app-build

        - name: deploy to azure
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.SWA_TOKEN }}
            action: "upload"
            app_location: "react-app-build/dist" # Absolute path to the downloaded artifact containing built files
            api_location: "" # Api source code path - optional
            output_location: "" # Built app content directory - set to empty since artifact contains the built files directly
            skip_app_build: true # Skip building since the app is already built and uploaded as artifact


        

        