name: React-Artifact-output-cache
on:
  push:
    branches: ["main"]
    paths:
      - 'reactoct/**'
    
  workflow_dispatch:

env:
  workingdir: './reactoct'

jobs:
#   npm-test:
#     runs-on: [self-hosted, linux, x64]
# #    runs-on: ubuntu-latest
#     steps:
#       - name: checkout code
#         uses: actions/checkout@v3

#       - name: caching dependencies
#         id: cache
#         uses: actions/cache@v4
#         with:
#           path: |
#             ~/.npm
#             node_modules
#           key: ${{ runner.os }}-node-${{ hashFiles('./reactoct/package-lock.json') }}  
#           restore-keys: |
#             ${{ runner.os }}-node-

#       - name: Install dependencies
# #        if: steps.cache.outputs.cache-hit != 'true'
#         run: npm install
#         working-directory: ${{ env.workingdir }}

#       - name: linting
#         run: npm run lint
#         working-directory: ${{ env.workingdir }}
              
#       - name: testing-the-code
#         id: test
#         run: npm test
#         working-directory: ${{ env.workingdir }}

#       - name: output test failure artifact
#         if: steps.test.outcome == 'failure'
#         uses: actions/upload-artifact@v4
#         with:
#           name: test-report
#           path: test.json

  build:
#    runs-on: [self-hosted, linux, x64]
    runs-on: macos-latest
#    needs: npm-test
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      
      # - name: install nodeJs
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18

      - name: caching dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./reactoct/package-lock.json') }}  
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
        working-directory: ${{ env.workingdir }}

      - name: Setup Java 
        uses: actions/setup-java@v3 
        with: 
          distribution: 'temurin' 
          java-version: '17'
      - name: Setup Ruby 
        uses: ruby/setup-ruby@v1 
        with: 
          ruby-version: '3.2' 
          bundler-cache: true
          
      - name: Install Fastlane 
        run: |
         gem install fastlane -NV
        
      - name: Android Build (APK + AAB) 
        run: | 
         mkdir android && cd android
         fastlane build 
         cd ..
         
      - name: Upload Android AAB Artifact 
        uses: actions/upload-artifact@v4 
        with: 
          name: android-aab 
          path: android/app/build/outputs/bundle/release/*.aab

      - name: Upload Android APK Artifact 
        uses: actions/upload-artifact@v4 
        with: 
          name: android-apk 
          path: android/app/build/outputs/apk/release/*.apk 
          
      - name: iOS Build (IPA) 
        run: | 
         mkdir ios && cd ios 
         fastlane build
         cd ..

      - name: Upload iOS Artifact 
        uses: actions/upload-artifact@v4 
        with: 
          name: ios-ipa 
          path: ios/build/*.ipa
      
      - name: build
        run: npm run build
        working-directory: ${{ env.workingdir }}

      - name: artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{ env.workingdir }}/build/


    
