
name: NodeJs Build

on:
  push:
    branches: ["main"]
    paths:
      - 'react-proj/**'

  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: install nodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: change working directory
        run: cd react-proj

      - name: Install dependencies
        run: npm install
      
      - name: run tests
        run: npm test
        
